- src/app.js
- src/controllers/authControllers.js
- src/routes/auth.js
> import 문제 해결

- .vscode/settings.json
- prisma/schema.prisma
- src/app.js
- src/controllers/momentControllers.js
- src/routes/momentRoutes.js
DB 수정 npx prisma db push 필수!!
1. 생성 post /buckets/:bucketID/moment
모멘트를 생성할 땐 다음 조건을 확인한다(1. 달성형 여부, 2. 도전 중인 리스트 여부(true)
2. 조회 get /buckets/:bucketID/moment
사용자가 사용 X 내부 사용
3. 달성 patch /moments/:momentID
모멘트 달성 시 image url 저장 (인증 사진 업로드)
인증 사진 업로드 시 모멘트를 달성했습니다, isCompleted = true
이슈 사항
버킷리스트 기능의 수정이 필요함
1. 모멘트 달성 % 는 버킷리스트에서 저장 및 처리 필요
2. 도전리스트(3개)의 조건 처리 또한 버킷리스트 로직 수정 필요
3. 전체적인 버킷리스트 DB 수정이 필요함 (DB설계서 참고)
> 모멘트 기능 구현 완료 - 생성, 조회, 달성 (인증 사진 전송 포함)

- prisma/schema.prisma
- src/app.js
- src/controllers/bucketControllers.js
- src/controllers/momentControllers.js
- src/routes/momentRoutes.js
1. 버킷리스트 생성 POST /
2. 버킷리스트 조회 GET /bucketID
3. 버킷리스트 도전리스트 변환
4. 모멘트 설정 (bucketID 필요) POST /moments/bucketID/moments
5. 모멘트 달성 PATCH /moments/momentID
- 상세한 예외처리는 수정 필요
> bucket, moment 구현

- src/controllers/bucketControllers.js
- src/controllers/momentControllers.js
moment와 bucket controller 이미지 업로드 부분 수정
> s3 image 연결 수정

- src/controllers/bucketControllers.js
- src/controllers/momentControllers.js
- src/routes/momentRoutes.js
- 모멘트 completedMomentsCount 오류 수정
정상적인 계산 확인
- 버킷, 모멘트 isCompleted=true 오류 수정
-> 사진이 올라가도 false였던 오류 -> 로직 수정으로 true 확인
- getCompleteBuckets 생성 및 라우터 수정
홈화면에서 이용할 complete buckets 갯수 count 함수
> count 및 isCompleted 오류 수정 완료, getCompleteBuckets 생성

- src/controllers/bucketControllers.js
- src/controllers/momentControllers.js
버킷리스트의 모멘트가 다 달성했는데도 불구하고 isCompleted 가 true로 변하지 않는 오류 해결
> bucket isCompleted 반복형 오류 수정

- src/routes/momentRoutes.js
복잡한 라우터 부분 수정
POST moments/:bucketID 생성
GET moments/:bucketID 조회
> 모멘트 라우터 수정

- src/controllers/bucketControllers.js
- src/routes/momentRoutes.js
GET /api/bucket/all/buckets
전체 버킷리스트 조회 가능 API 추가
> 유저의 버킷리스트 전체 조회 구현

- src/controllers/friendControllers.js
주희님이 하신 유저의 전체 버킷리스트 조회 구현 + 친구 삭제 코드 보완
GET /api/bucket/all/buckets
> fix - 친구 삭제 코드 보완

- src/controllers/bucketControllers.js
- src/routes/momentRoutes.js
DELETE /api/bucket/:bucketID
- 해당 버킷리스트와 반복형일 경우 버킷리스트의 모멘트들도 자동 삭제되도록 함
버킷리스트 찾을 수 없을 경우 예외처리
> 버킷리스트 삭제 구현

- src/controllers/friendControllers.js
첫 번째 요청이 실패했지만, 데이터는 일부 저장되는 것으로 예상
500 에러 발생 -> 409(이미 처리) 발생
예상되는 에러 발생의 추가적인 예외처리 작성
- 500 오류 방지 → feed, user, friend 존재 여부 체크
- 409 오류 → 트랜잭션 적용하여 실패 시 롤백
> 응원하기 오류 확인 추가 예외처리

- src/controllers/bucketControllers.js
- src/controllers/momentControllers.js
1) 버킷 삭제 res에 type도 추가 요청 (수정 완료)
2) 모멘트 main API res에 isCompleted 추가
> 버킷 삭제 res 추가 + 모멘트 main res 추가

- prisma/schema.prisma
- src/controllers/friendControllers.js
- src/routes/friendRoutes.js
기존에 PR 올린 것에 반영이 안되어서 다시 올렸습니다
> fix - 친구 피드 응원하기 수정 (add안해서 다시 올림)

- prisma/schema.prisma
- src/controllers/momentControllers.js
1) 모멘트 달성 시 이미지 주소가 db에 저장이 안되어 res에서 null이 뜸
-> 예외처리 및 코드 수정
2) bucket 필요없는 필드 삭제
npx prisma db push 필요
momentCount, completedMomentsCount 삭제 -> 실시간 계산
> 모멘트 이미지 주소 + bucket DB 수정

- src/controllers/friendControllers.js
기존 친구 노크하기 수정
1. Feed테이블 사라짐으로 인해 moment테이블 사용하도록 변경
2. 자세한 로직은 연결하면서 수정필요할 것 같습니다
> fix - 친구 노크하기 수정 (로직은 추후에 수정 필요할듯)

- src/controllers/momentControllers.js
- moment endDate 기한이 지났으면 isChallenging 필드를 false로 바꿔주는 예외처리 추가
- getMomentsByBucket과 getChallengingBucketsAndMoments 에 추가
> moment endDate 예외처리

- src/controllers/momentControllers.js
전) 모멘트 생성 시 DATE 형식으로 날짜를 받았어야함
1) 모멘트 생성시 2024-02-06과 같은 string 형태로 받아도 자동으로 date형식으로 바꿔주는 로직 추가
2) startDate는 해당 날짜 00시 00분 00초 부터로 설정되며, endDate는 해당 날짜 23시 59분 59초로 자동 설정되도록 함
3) bucket의 start와 end 날짜도 동일하게 적용
> 모멘트 생성 날짜 설정 수정

- src/controllers/homeControllers.js
- src/routes/homeRoutes.js
홈 화면 달성 구현 (GET /api/home)
response : 달성한 버킷갯수, 달성한 버킷의 비율
> 홈 달성 현황 구현

- src/controllers/notificationController.js
- src/routes/homeRoutes.js
**Long Polling 방식의 문제점** 
- 클라이언트 측에서 계속해서 요청을 해야 한다는 점이 번거로움 
해결방안 : **SSE 방식** 
- 서버 측에서 10초 간격으로 데이터 전송 (클라이언트가 계속 요청 X) 
- HTTP 방식이라 연결도 WebSocket보다 쉬울 것으로 예상 !
> fix: 실시간 알림 개수 전송 SSE 방식으로 수정

- src/controllers/notificationController.js
- src/routes/homeRoutes.js
Reverts codeit-momentum/moment-back#91
> Revert "fix: 실시간 알림 개수 전송 SSE 방식으로 수정"

- src/controllers/friendControllers.js
- src/controllers/momentControllers.js
- src/routes/momentRoutes.js
1) 노크하기 버킷리스트가 없을경우의 예외처리 추가
2) 버킷의 도전중인 리스트 count 값 api 추가(GET /api/bucket/challenging/count)
momentRoutes.js 와 momentControllers.js 수정
> 노크하기 예외처리 추가 및 challenging count API 추가

- src/controllers/feedControllers.js
> feed 에러 수정

- src/controllers/userControllers.js
> 회원 탈퇴 cascade 트랜잭션 적용

- package-lock.json
- package.json
- prisma/schema.prisma
- src/controllers/friendControllers.js
- src/controllers/momentControllers.js
1) DB 수정 - completedAt DATETIME 추가
npx prisma db push 필요
2) moment 달성 로직에 updatedAt 이 아닌 completedAt이 기록되도록 수정
3) 버킷리스트가 없을 경우에도 노크 가능하도록 수정 (오류 예외처리 삭제)
> moment 달성 시 completedAt 추가

- src/app.js
- src/controllers/authControllers.js
app.js 의 cors 설정 수정
authControllers.js 의 refreshtoken cookie res domain값 추가 및 수정
> cors, domain 수정

- prisma/prisma.js
- prisma/schema.prisma
- src/controllers/homeControllers.js
일주일 모멘트 조회 문제점
1. 하루에 모먼트 완료 했을 때 체크 표시 X => some 수정 
2. 모먼트가 완료되었을 때 해당 모먼트를 가지고 있는 모든 날짜가 체크되는 문제 => 달성한 날짜에만 체크되도록 수정 !
> fix: 홈 화면 일주일 모멘트 조회 수정 완료

- package-lock.json
- package.json
- src/controllers/bucketControllers.js
- src/controllers/feedControllers.js
- src/controllers/friendControllers.js
- src/controllers/momentControllers.js
UTC 를 한국 시간 기준으로 수정 진행
- 모듈 설치로 npm install 필수
- moment-timezone 모듈 사용 koreaNow 변수
> update, complete, create 한국시간 기준으로 수정

- src/controllers/feedControllers.js
> feed cheer 부분 수정

- src/controllers/feedControllers.js
친구 피드 모멘트 날짜 받아오는 부분 전) updatedAt 다른 활동과 겹치는 이슈로 completedAt으로 변경
따라서 피드의 모멘트 정보를 받아오는 부분도 updatedAt이 아닌 completedAt으로 받아오도록 변경
> 친구 피드 모멘트 달성 날짜 변경

- src/controllers/homeControllers.js
- src/controllers/notificationControllers.js
- src/routes/homeRoutes.js
> fix : 읽지 않은 알림 개수 조회 방법 수정 
