- prisma/schema.prisma
- src/app.js
- src/controllers/authControllers.js
- src/routes/auth.js
- src/routes/authRoutes.js
1. Prisma에서 User 정보 일부 수정
2. .env에서 REDIRECT_URI=http://localhost:3000/auth/kakao/callback
3. .env에서 DATABASE_URL은 mongoDB Atlas 서버 연결
4. auth.js를 authRoutes.js로 파일명 변경
5. 테스트용으로 인가코드 받아오는 코드 (라우트) 구현
> feat - 카카오 로그인 구현

- package-lock.json
- package.json
- src/app.js
- src/controllers/authControllers.js
- src/controllers/jwtControllers.js
- src/middlewares/jwtMiddlewares.js
- src/routes/authRoutes.js
1. 기존 POST http://localhost:3000/auth/kakao-login/user랑 받아온 카카오 액세스 토큰을 통해 유저 로그인을 하면, 로그인한 사용자의 정보를 받아오는 것에서, JWT 액세스 토큰과 쿠키에 리프래시 토큰 발급 받도록 구현 => (response에 사용자 정보랑 JWT 액세스 토큰, 쿠키에 리프래쉬 토큰)
2. .env파일에서 JWT 관련 설정으로 아래 사항 추가
JWT_SECRET=7909b12f13842de0e4f3cc4df1f3ae95ca430fd3964b51fa52cf6e4181a10a23625b5e9188d8618747422482a7472651a139a49df7e2dabfad0e0cb6c2684080
JWT_REFRESH_SECRET=09f124822eecd6ec3e0275734e83a2c1d025a8ac60248f3dbc3e25bd9fb58c531614126cbc7717f9642bbf65228113602470e71b435caa5c7a536ebaa1e83e3
JWT_ACCESS_EXPIRATION=1h
JWT_REFRESH_EXPIRATION=7d
4. app.js에서 쿠키 사용하기 위한 cookie-parser 추가
5. jwtMiddleware에 jwt토큰 인증 미들웨어 생성 => 추후 개발하는 기능의 라우터에 router.use(jwtMiddleware); 하면 자동으로 인증 미들웨어 적용 (jwt 토큰)
Ex: (테스트용 라우트)
GET http://localhost:3000/auth/profile  
Authorization: Bearer (액세스 토큰) …
> feat - 카카오 로그인 + JWT 토큰 추가

- .env.development
- .env.production
- package-lock.json
- package.json
- src/.gitignore
- src/app.js
- src/server.js
수정 내역
개발 환경과 배포 환경 구분을 위한 dotenv 설정 변경
모든 환경(window, macos, linux)에서 가능하도록 cross-env 사용
server.js 수정
필요한 package 설치 package.json 참고
테스트 실행 방법
env파일 두가지 추가(.env.development, .env.production)
1-2. 내용은 보안상의 이유로 내부에서 공유(REDIRECT_URI, CLIENT_ID, NODE_ENV)
npm install 을 통해 package 설치
개발 환경을 실행 npm run start:dev
배포 환경을 실행 npm run start:prod
conflict 해결
git reset --hard main : main으로 강제 덮어씌우기
재구현
> re 개발환경 분리 (conflict 해결)

- package-lock.json
- package.json
- prisma/schema.prisma
- src/controllers/authControllers.js
1. package.json에서 기존 npm run start:dev나 npm run start:dev prod시, nodemon 사용하도록 변경
2. prisma파일에 User 모델에 friendCode 속성 추가 (Unique, Not-Nullable)
3. 기존 카카오 사용자 처리 (데이터베이스 저장/조회) + (JWT 토큰 발급)에서 친구코드 발급 추가 (랜덤 대문자 4자리 + 숫자 4자리)
> feat - 회원가입/로그인에 친구 코드 추가

- package-lock.json
- package.json
- prisma/schema.prisma
- src/config/s3config.js
- src/controllers/authControllers.js
- src/server.js
1. Prisma 변경시 npx prisma db push 하시면 반영됩니다.
2. AWS S3 클라이언트 설정 추가 (s3config.js)
2.1 AWS 관련 .env설정은 노션 개발/BE/기초 작업(설정) 에 업데이트 해놓았습니다. (.env파일에 추가)
3. 기존 회원가입/로그인시 USER DB에 저장되는 정보 변경 (처음 접속시)
3.1 테스트용 이메일 => 카카오계정에서 이메일 받아오는것으로 변경 
3.2 사용자 닉네임 => handleKakaoUser에서 사용자의 이메일의 @ 앞부분에서 따온 것으로 사용자 기본 닉네임 설정
3.3 사용자 프로필이미지 => handleKakaoUser에서 *테스트용 기본 프로필 이미지 URL*을 사용 (AWS S3에 업로드된 상태)
> feat - AWS S3 버킷 사용자 설정 추가 + Prisma USER DB 변경/저장값 추가

- package-lock.json
- package.json
- prisma/schema.prisma
- src/app.js
- src/controllers/userControllers.js
- src/middlewares/jwtMiddlewares.js
- src/routes/userRoutes.js
*마이페이지 경로는 API 명세서 나오는대로 수정 필요*
1. 마이페이지 관련 컨트롤러, 라우트 생성 (userControllers.js, userRoutes.js)
2. 마이페이지 관련 API => 모두 JWT 토큰 인증 필요 => JWT 토큰으로 사용자 인증 후 진행하도록 인증 미들웨어 적용 router.use(jwtMiddleware); (앞으로 항상 Authorization Bearer {토큰} 필요
3. 현재 사용자 정보 조회 (GET '/mypage/profile') 
GET http://localhost:3000/myPage/profile
Authorization: Bearer 토큰
4. 현재 사용자 닉네임 변경 (PUT '/myPage/profile/update-nickname')
PUT http://localhost:3000/myPage/profile/update-nickname
Content-Type: application/json
Authorization: Bearer 토큰
{
"newNickname": "test9525"
}
5. 현재 사용자 프로필 이미지 변경 (PUT '/myPage/profile/update-profileImage')
- 프로필 이미지 업로드 X시 기존의 프로필 이미지로 유지
PUT http://localhost:3000/myPage/profile/update-nickname
Content-Type: multipart/form-data
Authorization: Bearer 토큰
"profileImage": (이미지 파일 업로드)
6. 기존의 인가 코드를 통한 …
> feat - 사용자 조회 & 닉네임 수정 & 프로필 사진 수정 구현

- prisma/schema.prisma
- src/app.js
- src/controllers/friendControllers.js
- src/middlewares/jwtMiddlewares.js
- src/routes/friendRoutes.js
1. 마이페이지 관련 라우트 '/myPage' 에서 /api/myPage'로 수정
2. prisma에 FriendRequest, Friend 테이블 추가
- npx prisma db push로 적용
3. friendControllers.js, friendRoutes.js 추가 ('/api/friends')
4. 사용자 친구 목록 조회 구현 (GET '/api/friends')
5. 친구 추가 요청 구현 (POST '/api/friends') (friendCode req로 받아서 요청 보냄)
6. 친구 요청 목록 조회 (GET '/api/friends/requests') (내가 요청한것과, 상대방이 요청 보낸 것 모두 확인 가능) (현재는 Pending인 것만 확인 가능하도록 구현)
7. 사용자 친구 요청 수락/거절 구현 (PATCH '/api/friends/requests/:friendRequestID') (req에 status값으로 ACCEPTED, REJECTED를 받아와서 수락/거절 구현) 수락시 Friend 테이블에 친구관계 생성, 거절시 status만 REJECTED로 변경
> feat - 사용자 친구 목록 조회, 친구 추가 요청, 친구 요청 목록 조회, 친구 요청 수락/거절 구현 & fix - 사용자 친구 목록 조회 수정 & jwt미들웨어 리프래시 토큰 재발급 수정

- src/app.js
- src/controllers/userControllers.js
- src/routes/userRoutes.js
1. 기존 마이페이지 API 라우트 수정 (API 명세서 바탕으로 수정)
- GET '/api/users' (현재 사용자의 정보 조회)
- PATCH '/api/users/profileImage (현재 사용자의 프로필 이미지 수정) (기존 PUT => PATCH 변경)
- PATCH '/api/users/nickname (현재 사용자의 닉네임 수정) (기존 PUT => PATCH 변경)
- GET '/api/users/friendCode (현재 사용자의 친구 코드 조회 ) (그냥 위의 GET '/api/users' 에서 friendCode도 나오므로 해당 라우트로도 친구 코드 조회 가능)
> fix - 마이페이지 경로 변경 및 현재 사용자의 친구 코드 조회 기능 추가

- package-lock.json
- package.json
- prisma/schema.prisma
- src/controllers/friendControllers.js
- src/routes/friendRoutes.js
1. (package.json) node-cron, moment : 날짜 리셋과 설정을 위함 -> 실행 시 npm install 필수
2. 로그인 접속 상태
3. 친구 삭제 기능 DELETE /api/friends
- jwt 토큰 필요(user)
- 한번 삭제될 경우 친구 재신청 불가
- 삭제가 성공할 경우 다음과 같은 결과
4. 노크 기능 POST /api/friends/knock
- jwt 토큰 필요(user)
- 노크는 일주일(월-일)에 한번만 가능(매주 월요일에 리셋)
- 노크를 두 번할 경우 알람은 전송되지 않으며 403 res
- 피드가 없을 경우 knock 메세지가 전송
- 피드가 있을 경우 다음과 같이 res
> 친구 삭제 기능, 친구 노크하기 기능 구현

- prisma/schema.prisma
- src/controllers/friendControllers.js
1. 기존 Prisma에서 status로 DELETED 추가
enum FriendRequestStatus {
PENDING // 요청 대기 상태
ACCEPTED // 요청 수락 상태
DECLINED // 요청 거절 상태
DELETED // 친구 삭제된 상태
}
2. 친구 추가 요청시 상대가 보낸 요청이 존재해도 친구 요청이 중복으로 보내지는 버그 수정
3. 친구 삭제시 해당 친구 관계를 맺게 만들어준 friendRequest 테이블에서 해당 요청을 찾아서 status DELETED로 변경
> fix - 친구 추가 요청 버그 수정 & 친구 삭제 시 friendRequest status DELETED 추가

- prisma/schema.prisma
- src/controllers/friendControllers.js
- src/routes/friendRoutes.js
1. Prisma의 FriendRequest 테이블 삭제
2. 기존 친구 추가 로직 수정
- 친구 추가 요청 => FriendRequest테이블 데이터 추가 => 상대방의 친구 요청 수락/거절 결정 => 수락시 Friend 테이블에 친구 관계 추가
3. 수정된 친구 추가 로직
- 친구 추가 => 곧바로 Friend 테이블에 친구 관계 추가
4. 수정된 친구 추가 로직으로 인해 일부 메소드 수정/삭제
- 친구 추가 요청 메소드/라우트 => 친구 추가 메소드/라우트 (POST /api/friends)
- 친구 추가 요청 목록 조회 삭제 (GET /api/friends/requests)
- 친구 추가 요청 수락/거절 삭제 (PATCH /api/friends/requests/:requestID)
- 친구 삭제 메소드/라우트 유지 => 대신 FriendRequest에서 변경하는 로직만 삭제 (Friend관계 삭제만 하는 것으로 변경)
> fix - 친구 요청기능 삭제

- prisma/schema.prisma
- src/controllers/bucketControllers.js
- src/controllers/momentControllers.js
- 로직만 수정했기 때문에 (사진 인증시 달성으로 처리) 기본 실행 방법과 사용 방법은 동일함
- + moment 생성 시 start와 end date 받아오기
-  prisma db 디폴트값 수정, db 저장 시 모든 필드가 뜨도록
- 필요없는 로직 수정
momentsCount : 전체 모멘트 수
completedMomentsCount: 달성한 모멘트 수
홈화면 및 모멘트 화면 % 사용 시 참고
> moment count 로직 수정 및 prisma db default 수정

- prisma/schema.prisma
momentsCount와 completeMomentsCount 갯수가 DB 직접 저장하지 않고 실시간 계산을 하는 방식으로 바꿈.
getBucketDetail - 조회 API를 사용하면 momentsCount와 completeMomentsCount 를 확인할 수 있음
> momentsCount DB 삭제, 실시간계산 로직으로 사용

- src/controllers/bucketControllers.js
- src/controllers/friendControllers.js
- src/controllers/userControllers.js
- src/routes/friendRoutes.js
1. bucket 에서 isChallenge를 활성화 한 후 모멘트를 생성하기 전(전체: 0, 달성: 0)으로 부터 발생하는 isCompleted=true 버그 해결
-> 0을 예외처리하여 모멘트를 생성하기 전에 isCompleted상태는 false가 되도록
2. 프론트 측에서 요구한 친구확인용 로직 구현
- 친구의 친구코드 입력은 친구 신청과 동일하게 되어있지만, 수락하지 않고 닉네임만 먼저 반환해주는 기능
- POST /api/friends/check-friendCode
- request: friendCode / response: nickname
- 테스트 및 예외처리 완료
> bucket isCompleted 버그 수정, check-friendCode 로직 구현

- src/routes/momentRoutes.js
버킷리스트 상세 조회와 선택한 모멘트 상세 조회의 라우터가 겹치는 이슈 발생
모멘트 상세 조회의 라우터를 수정 moments -> moment       GET /api/bucket/moment/:momentID
> 모멘트 상세 조회 라우터 수정

- src/controllers/bucketControllers.js
- src/routes/momentRoutes.js
1) 기존 전체 조회 삭제
2) 반복형과 달성형 따로 받아오는 API
3) 반복형 버킷리스트 전체 목록 조회 GET api/bucket/all/repeat
content, isChallenging, isCompleted, bucketID
4) 달성형 버킷리스트 전체 목록 조회 GET api/bucket/all/achievement
content, isCompleted, bucketID
- 로그인이 되어있는 user의 버킷 목록을 조회
- 정렬은 추후 수정 예정
> 버킷리스트 전체 조회 분류(달성형, 반복형)

- src/controllers/momentControllers.js
- src/routes/momentRoutes.js
1) 모멘트 전체 완료시 도전리스트에서 계속 true로 있는 버그 수정 -> false로 처리
2) 모멘트 메인 페이지의 정보 조회 기능 구현
- moment: photoUrl, content
- bucket: content, momentCount, completedMomentsCount, bucketID
버킷리스트는 isChallenging이 true인 버킷만(도전 중인 버킷)
모멘트는 now가 startDate와 endDate사이인 모멘트만(진행 중인 모멘트)
- count들은 전부 실시간 계산 로직
3)
> 모멘트 전체 완료시 도전 리스트에서 제외 (버그 수정) + 모멘트 기능 메인페이지 버킷, 모멘트 조회 기능 구현

- src/middlewares/jwtMiddlewares.js
기존 피드 응원하기 POST ('/api/friends/cheer/:feedId') 
- feed테이블의 feedID 사용
수정한 피드 응원하기 POST ('/api/friends/cheer/:friendId/:momentId')
- feed 테이블 삭제
- 파라미터로 friendId, momentId 받아옴
- friendFeed 테이블의 feedID 대신 momentID로 변경
- friend테이블에서 친구 관계 확인
- friend관계 확인 후, 해당 친구의 moment인지 확인
- moment가 존재해도 해당 친구사용자 모멘트가 아니면 오류
+ JWT미들웨어 토큰 만료 에러 401로 통일
+ Prisma 수정했으므로, npx prisma db push 필요시 사용
POSTMAN API에서 친구(피드)에서 친구 응원하기로 확인 가능
> fix - 친구 피드 응원하기 수정

- src/controllers/feedControllers.js
- src/controllers/friendControllers.js
1. 친구 피드 조회 => 응원 여부 포함 수정 + 버킷이름, 모멘트 이름 같이 출력되도록 변경 (bucketContent, momentContent, cheered 추가 출력)
2. 친구 노크하기 로직 수정
- createdAt 기준 X, updateAt 최근 7일 이내에 isCompleted한 피드(모멘트)가 있으면 노크 X
- 간단하게 updatedAt 최근 7일이내올라온 피드(모멘트)가 없는 경우 응원하기 가능
> fix - 친구 피드 조회할때 응원여부 포함 & 노크하기 로직 수정

- .gitignore
- package-lock.json
- package.json
- src/controllers/homeControllers.js
- src/controllers/notificationController.js
- src/routes/homeRoutes.js
- src/server.js
1. Long Polling 변경
- Web Socket API 연동 실패 => Long Polling 방식으로 수정 
- 30초마다 클라이언트 측에서 요청 
- 30초 동안 새로운 알림이 생성 되면 알림 개수 갱신 / 변동 없으면 그대로 보낸다. 
2. 일주일 모멘트 완료 현황 조회 수정 
- 문제점
a. new Date는 날짜만 입력 받았을 때 UTC 시간대로 인식하여 처리
b. startOfWeek와 endOfWeek 방식을 사용하면 UTC 시간으로 처리하고 로컬 시간대로 반영하여 날짜가 밀리는 문제 발생 
- 해결방안
날짜를 입력 받으면 해당 주의 월요일과 일요일을 일일이 구하자 ! ( getDay()를 활용하여 계산 하는 방식 사용)
> fix : 실시간 알림 개수 전달 Long Polling으로 변경 & 일주일 모멘트 완료 현황 조회 수정 

- src/controllers/feedControllers.js
피드 리스폰스에 isKnock을 추가하면서, DB에 데이터들을 추가해 테스트해보니 cheered를 불러오는 로직에 문제가 발견되어 조치하였습니다!
> 피드 리스폰스에 isKnock 추가, cheered 오류 해결
